### ISSUE TITLE
Errors everywhere: `Unknown custom element: <v-XXXXX> - did you register the component correctly?`

### ISSUE THREAD

**Issue by kuanyen** [vuetifyjs/vuetify-loader#46]
- `vue 2.6.10`
- `webpack 4.19.1` (Via vue-cli)
- `vuetify 1.5.7`
- `vuetify-loader 1.2.1`
- `typescript 3.3.3`
- run with `vue-cli-service serve`

I followed [this official document](https://vuetifyjs.com/en/framework/a-la-carte) to try to make my existing Vue project able to lazy-load Vuetify components. However:

1. Compilation has no error message at all.
2. Most of Vuetify component are failed to load with error message `Unknown custom element: <v-XXXXX> - did you register the component correctly? `

![Screenshot_20190403_190142](https://user-images.githubusercontent.com/20762725/55474853-d6061b00-5644-11e9-8ab7-19578f717fa6.png)

This is the diff:
![Screenshot_20190403_191729](https://user-images.githubusercontent.com/20762725/55474964-309f7700-5645-11e9-8156-dc8b9590c29c.png)

**Comment by mayank-shaan** [comment]
+1

**Comment by jacekkarczmarczyk** [comment]
We need an actual boiled down repo to investigate, please provide one and we'll reopen the issue if it appears to be a bug

This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
