### ISSUE TITLE
Option to specify the target Vuetify directory in node_modules

### ISSUE THREAD

**Issue by ttonyh** [vuetifyjs/vuetify-loader#82]
Since npm v6.9.0, we are now able to specify multiple versions of the same package. It would be very useful if we could set an option, that refers to the version of Vuetify you want to target, when using multiple versions, in the same project.

REF:
- https://github.com/npm/rfcs/blob/latest/implemented/0001-package-aliases.md#detailed-explanation
- https://stackoverflow.com/questions/26414587/how-to-install-multiple-versions-of-package-using-npm

**Comment by KaelWD** [comment]
What is the use case for this? You can already use webpack's `resolve.alias` to convert `'vuetify/lib'` into `'vuetify-next/lib'`

**Comment by Heniker** [comment]
Not sure if actually related to this issue, but I think I am looking for something similiar.

My use case is that I use webpack `resolve.modules` and `resolveLoaders.modules` to specify several node_modules locations across my monorepo. The problem is that `vuetify-loader` uses `vue` and `vuetify` peerDependencies, and it seems that webpack `resolveLoaders.modules` doesnt affect plugins section in webpack.config. So I can't tell `vuetify-loader` where to find `vue` and `vuetify`.

More visual example of my file structure:
```
.
├── build
│   ├── node_modules
│   └── webpack.config.json
└── src
    ├── App.vue
    ├── main.ts
    └── node_modules
```

So in the `build` folder I have `vuetify-loader`, while `vue` and `vuetify` are in `src`

**Comment by KaelWD** [comment]
If you're using package aliases install the version you want to be autoloaded as just `vuetify`

@Heniker I suggest using yarn workspaces instead
